// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCsXn-bZeBom18A09QzE18UtADn4j1etA',
    appId: '1:975090649072:android:547e3ef8b624a278393f35',
    messagingSenderId: '975090649072',
    projectId: 'smoothapod',
    storageBucket: 'smoothapod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWsw5WbJH6nyh0ZL8mipDHHxBBbLKbB0Y',
    appId: '1:975090649072:ios:30f3afed5235e083393f35',
    messagingSenderId: '975090649072',
    projectId: 'smoothapod',
    storageBucket: 'smoothapod.appspot.com',
    iosClientId: '975090649072-jj6q9b6gehovgoq8sie9ep3k6o4pegjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.smoothApod',
  );
}
