name: test-my-app
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: create .env file
        run: echo ${{ secrets.ENV_FILE_CONTENT }} | base64 -d > .env

      - name: run integration test
        run: flutter test
