name: test-my-app
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: create .env file
        run: echo "$ENV_FILE_CONTENT" > .env
        env:
          ENV_FILE_CONTENT: $ENV_FILE_CONTENT

      - name: run integration test
        run: flutter test --coverage
